
### get user

GET http://localhost:3000/users/1

#### create user

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "johndoe3",
  "email": "john3@doe.com",
  "password": "12345678"
}

#### login

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "johndoe3",
  "password": "12345678"
}
